apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfig
data:
  DB_NAME: mydatabase
  DB_USER: myuser
  DB_HOST: postgresql-service
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: mypassword
type: Opaque
data:
  my-password: bXlwYXNzd29yZA==